version: 0.2

env:
  variables:
    FUNCTION_NAME: "hello-lambdas"
    AWS_REGION: "us-east-1"
    CLOUDFORMATION_FILE: "cloudformation.yml"
    STACK_NAME: "cicd-lambda-stack"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing NPM dependencies...
      - npm install
  pre_build:
    commands:
      - set -e  # Exit immediately if a command exits with a non-zero status
      - echo Testing...
      - npm run test
      - echo Validating Code Style...
      - npm run lint
      - echo Validating Format...
      - npm run prettier
      - aws cloudformation validate-template --template-body file://$CLOUDFORMATION_FILE
      - echo Validating Cloudformation status
      - status="$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region $AWS_REGION --query "Stacks[0].StackStatus")"
      - echo $status
  build:
    commands:
      - set -e  # Exit immediately if a command exits with a non-zero status
      - echo Building...
      - npm run build
  post_build:
    commands:
      - echo Build of lambda $FUNCTION_NAME is complete.