version: 0.2

env:
  variables:
    FUNCTION_NAME: "hello-lambdas"
    AWS_REGION: "us-east-1"
    API_GTW_ID: "7r4dquq6pl"
    ACCOUNT_ID: "846286757852"
    DYNAMO_TABLE_NAME: "cicd-dynamodb-table"
    CLOUDFORMATION_FILE: "cloudformation.yml"
    STACK_NAME: "cicd-lambda-stack"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Testing...
      - npm run test
      - echo Validating Code Style...
      - npm run lint
      - echo Validating Format...
      - npm run prettier
      - echo Getting Open API definition...
      - echo Adding environment variables to Open API definition...
      - |
        #!/bin/bash
        # Read the template file
        template_file="api-docs.json"

        # Replace placeholders with environment variables
        sed -i '' -e "s/{{region}}/${AWS_REGION}/g" -e "s/{{account_id}}/${ACCOUNT_ID}/g" "$template_file"

        echo "OpenAPI definition generated successfully."
      - cat api-docs.json
      - status="$(aws cloudformation describe-stacks --stack-name $STACK_NAME --region $AWS_REGION --query "Stacks[0].StackStatus")"
      - echo $status
      - >
        if [[ $status == *"ROLLBACK_COMPLETE"* ]]; then
            echo "Stack $STACK_NAME is in ROLLBACK_COMPLETE state. Deleting the stack.";
            aws cloudformation delete-stack --stack-name $STACK_NAME --region $AWS_REGION;
            echo "Waiting for CloudFormation stack $STACK_NAME to be deleted...";
            aws cloudformation wait stack-delete-complete --stack-name $STACK_NAME --region $AWS_REGION;
            echo "CloudFormation stack $STACK_NAME deleted successfully.";
        fi
  build:
    commands:
      - echo Building...
      - npm run build
      - echo Updating Lambda function configuration to AWS...
      - aws lambda update-function-configuration --function-name $FUNCTION_NAME --handler src/index-hello-world.handler
      - echo Waiting for Lambda function configuration update to complete...
      - aws lambda wait function-updated --function-name $FUNCTION_NAME
  post_build:
    commands:
      - echo $FUNCTION_NAME
      - cd ./$FUNCTION_NAME/dist
      - ls -l
      - echo Updating Lambda function configuration to AWS...
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://$FUNCTION_NAME.zip --publish --output json
      - cd ../..
      - echo Deploy Lambda in API Gateway...
      - ls -l
      - aws apigateway put-rest-api --rest-api-id $API_GTW_ID --mode merge --no-fail-on-warnings --body fileb://api-docs.json
      - aws apigateway create-deployment --rest-api-id $API_GTW_ID --stage-name dev
      - >
        if aws dynamodb describe-table --table-name $DYNAMO_TABLE_NAME --region $AWS_REGION > /dev/null 2>&1; then
          echo "Table $DYNAMO_TABLE_NAME exists in region $AWS_REGION.";
        else
          echo "Table $DYNAMO_TABLE_NAME does not exist in region $AWS_REGION. Creating CloudFormation stack $STACK_NAME.";
          if aws cloudformation describe-stacks --stack-name $STACK_NAME --region $AWS_REGION > /dev/null 2>&1; then
            echo "Stack $STACK_NAME exists. Updating the stack.";
            aws cloudformation update-stack --stack-name $STACK_NAME --template-body file://$CLOUDFORMATION_FILE --region $AWS_REGION --capabilities CAPABILITY_NAMED_IAM;
            echo "Waiting for CloudFormation stack $STACK_NAME to be updated...";
            aws cloudformation wait stack-update-complete --stack-name $STACK_NAME --region $AWS_REGION;
            echo "CloudFormation stack $STACK_NAME updated successfully.";
          else
            aws cloudformation create-stack --stack-name $STACK_NAME --template-body file://$CLOUDFORMATION_FILE --region $AWS_REGION --capabilities CAPABILITY_NAMED_IAM
            echo "Waiting for CloudFormation stack $STACK_NAME to be created...";
            aws cloudformation wait stack-create-complete --stack-name $STACK_NAME --region $AWS_REGION;
            echo "CloudFormation stack $STACK_NAME created successfully.";
          fi
        fi