version: 0.2

env:
  variables:
    FUNCTION_NAME: "hello-lambdas"
    AWS_REGION: "us-east-1"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Testing...
      - npm run test
      - echo Validating Code Style...
      - npm run lint
      - echo Validating Format...
      - npm run prettier
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - echo Build of lambda $FUNCTION_NAME is complete.