AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template to create a DynamoDB table with On-Demand capacity.

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: cicd-dynamodb-table
      AttributeDefinitions: 
        - AttributeName: Id
          AttributeType: S
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Environment
          Value: Production
        - Key: Project
          Value: MyProject

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref MyDynamoDBTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt MyDynamoDBTable.Arn
